In [4]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [58]:
filePath = r"C:\Users\USER\OneDrive - The University of Memphis\Khulna University\SaintMartinIsland\Processed\Excel\K-fold\smi_24.csv"

In [60]:
df = pd.read_csv(filePath)
df

,Id,Class,GrndTrth,Classified,Classifi_1,LandUse,NDVI_SMI_2,b1_SMI_24,b2_SMI_24,b3_SMI_24,b4_SMI_24,b5_SMI_24,b6_SMI_24,b7_SMI_24,b8_SMI_24,b9_SMI_24,b10_SMI_24,b11_SMI_24,b12_SMI_24
0,0,1,0,0,0,Water,-0.304770,0.06230,0.07165,0.07565,0.04035,0.03540,0.02395,0.02370,0.02150,0.01865,0.01520,0.01260,0.00965
1,0,1,0,0,0,Water,-0.262519,0.06495,0.07135,0.07580,0.04160,0.03660,0.02740,0.02715,0.02430,0.02070,0.01845,0.01405,0.00950
2,0,1,0,0,0,Water,-0.276336,0.06510,0.07705,0.07605,0.04180,0.03710,0.02790,0.02845,0.02370,0.02280,0.01860,0.01325,0.00985
3,0,1,0,0,0,Water,-0.203884,0.06285,0.06670,0.06335,0.03720,0.03480,0.02780,0.02735,0.02460,0.02215,0.01845,0.01310,0.00935
4,0,1,0,0,0,Water,-0.224359,0.06420,0.06575,0.06395,0.03820,0.03570,0.02770,0.02820,0.02420,0.02330,0.02005,0.01335,0.00985
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
895,0,6,5,5,5,Sandy Water,0.139586,0.06080,0.07260,0.07830,0.07890,0.09170,0.09410,0.09725,0.10450,0.09580,0.03845,0.10625,0.09525
896,0,6,5,5,5,Sandy Water,0.219015,0.06010,0.06390,0.07485,0.06900,0.09085,0.10050,0.10205,0.10770,0.09840,0.03480,0.08970,0.07280
897,0,6,5,5,5,Sandy Water,-0.003973,0.06805,0.07355,0.07945,0.06950,0.07855,0.06545,0.06660,0.06895,0.05725,0.06385,0.04640,0.03100
898,0,6,5,5,5,Sandy Water,-0.355796,0.08295,0.08505,0.09540,0.08450,0.07220,0.04730,0.05070,0.04015,0.03995,0.04970,0.02140,0.01600
899,0,6,5,5,5,Sandy Water,0.073369,0.07645,0.08830,0.09735,0.09125,0.09570,0.08820,0.09070,0.10570,0.08620,0.06770,0.07330,0.06195

In [62]:
encoder = LabelEncoder()
df['LandUse'] = encoder.fit_transform(df['LandUse'])
print(df)

     Id  Class  GrndTrth  Classified  Classifi_1  LandUse  NDVI_SMI_2  \
0     0      1         0           0           0        5   -0.304770
1     0      1         0           0           0        5   -0.262519
2     0      1         0           0           0        5   -0.276336
3     0      1         0           0           0        5   -0.203884
4     0      1         0           0           0        5   -0.224359
..   ..    ...       ...         ...         ...      ...         ...
895   0      6         5           5           5        3    0.139586
896   0      6         5           5           5        3    0.219015
897   0      6         5           5           5        3   -0.003973
898   0      6         5           5           5        3   -0.355796
899   0      6         5           5           5        3    0.073369

     b1_SMI_24  b2_SMI_24  b3_SMI_24  b4_SMI_24  b5_SMI_24  b6_SMI_24  \
0      0.06230    0.07165    0.07565    0.04035    0.03540    0.02395
1      0.06495    0.07135    0.07580    0.04160    0.03660    0.02740
2      0.06510    0.07705    0.07605    0.04180    0.03710    0.02790
3      0.06285    0.06670    0.06335    0.03720    0.03480    0.02780
4      0.06420    0.06575    0.06395    0.03820    0.03570    0.02770
..         ...        ...        ...        ...        ...        ...
895    0.06080    0.07260    0.07830    0.07890    0.09170    0.09410
896    0.06010    0.06390    0.07485    0.06900    0.09085    0.10050
897    0.06805    0.07355    0.07945    0.06950    0.07855    0.06545
898    0.08295    0.08505    0.09540    0.08450    0.07220    0.04730
899    0.07645    0.08830    0.09735    0.09125    0.09570    0.08820

     b7_SMI_24  b8_SMI_24  b9_SMI_24  b10_SMI_24  b11_SMI_24  b12_SMI_24
0      0.02370    0.02150    0.01865     0.01520     0.01260     0.00965
1      0.02715    0.02430    0.02070     0.01845     0.01405     0.00950
2      0.02845    0.02370    0.02280     0.01860     0.01325     0.00985
3      0.02735    0.02460    0.02215     0.01845     0.01310     0.00935
4      0.02820    0.02420    0.02330     0.02005     0.01335     0.00985
..         ...        ...        ...         ...         ...         ...
895    0.09725    0.10450    0.09580     0.03845     0.10625     0.09525
896    0.10205    0.10770    0.09840     0.03480     0.08970     0.07280
897    0.06660    0.06895    0.05725     0.06385     0.04640     0.03100
898    0.05070    0.04015    0.03995     0.04970     0.02140     0.01600
899    0.09070    0.10570    0.08620     0.06770     0.07330     0.06195

[900 rows x 19 columns]

In [64]:
X = df[['b4_SMI_24', 'b3_SMI_24', 'b2_SMI_24', 'b8_SMI_24', 'NDVI_SMI_2']].values
y = df['LandUse'].values

In [66]:
from sklearn.model_selection import KFold, cross_val_score
from sklearn.ensemble import RandomForestClassifier

# Model
model = RandomForestClassifier()

# K-Fold
k = 5
kf = KFold(n_splits=k, shuffle=True, random_state=42)

# Perform cross-validation
cv_scores = cross_val_score(model, X, y, cv=kf)
print(f"K-Fold CV scores: {cv_scores}")
print(f"Mean score: {cv_scores.mean()}")

K-Fold CV scores: [0.92222222 0.91111111 0.9        0.92222222 0.92222222]
Mean score: 0.9155555555555557

In [68]:
from sklearn.model_selection import ShuffleSplit, cross_val_score

# Monte Carlo Cross-Validation
mc = ShuffleSplit(n_splits=10, test_size=0.2, random_state=42)
cv_scores = cross_val_score(model, X, y, cv=mc)
print(f"Monte Carlo CV scores: {cv_scores}")
print(f"Mean score: {cv_scores.mean()}")

Monte Carlo CV scores: [0.92222222 0.92777778 0.91666667 0.89444444 0.89444444 0.93333333
 0.9        0.92777778 0.92222222 0.91666667]
Mean score: 0.9155555555555555

In [70]:
from sklearn.model_selection import KFold
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_iris
import numpy as np

# Load dataset
X = df[['b4_SMI_24', 'b3_SMI_24', 'b2_SMI_24', 'b8_SMI_24', 'NDVI_SMI_2']].values
y = df['LandUse'].values

# Define model
model = RandomForestClassifier(random_state=42)

# Define K-Fold
k = 5
kf = KFold(n_splits=k, shuffle=True, random_state=42)

# Initialize metrics
omission_errors = []
commission_errors = []
accuracies = []

# Perform K-Fold Cross-Validation
for train_index, test_index in kf.split(X):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    
    # Train and predict
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    
    # Confusion Matrix
    cm = confusion_matrix(y_test, y_pred, labels=np.unique(y))
    TP = np.diag(cm)  # True Positives
    FN = cm.sum(axis=1) - TP  # False Negatives
    FP = cm.sum(axis=0) - TP  # False Positives
    TN = cm.sum() - (FP + FN + TP)  # True Negatives
    
    # Calculate omission and commission errors for each class
    omission = FN / (FN + TP) * 100  # Per class omission error
    commission = FP / (FP + TP) * 100  # Per class commission error
    
    # Append average omission and commission errors across all classes
    omission_errors.append(np.mean(omission))
    commission_errors.append(np.mean(commission))
    
    # Calculate accuracy
    accuracy = accuracy_score(y_test, y_pred)
    accuracies.append(accuracy)

# Calculate mean and standard error
mean_omission_error = np.mean(omission_errors)
mean_commission_error = np.mean(commission_errors)
mean_accuracy = np.mean(accuracies)

std_error_accuracy = np.std(accuracies) / np.sqrt(k)

# Print results
print(f"Mean Omission Error: {mean_omission_error:.2f}%")
print(f"Mean Commission Error: {mean_commission_error:.2f}%")
print(f"Mean Accuracy: {mean_accuracy:.2f}")
print(f"Standard Error of Accuracy: {std_error_accuracy:.4f}")

Mean Omission Error: 7.93%
Mean Commission Error: 7.83%
Mean Accuracy: 0.92
Standard Error of Accuracy: 0.0043