In [1]:
import pandas as pd
import numpy as np
from statsmodels.tsa.seasonal import STL
import matplotlib as plt

In [3]:
path = r"C:\Users\USER\OneDrive - The University of Memphis\Khulna University\SaintMartinIsland\Processed\Excel\Index_Sample.csv"

In [5]:
df = pd.read_csv(path)
df

,pointid,grid_code,Lat,Long,WAI_24,WAI_22,WAI_20,WAI_18,Turbidity_24,Turbidity_22,...,LST_20,LST_18,ARVI_18,EVI_24,EVI_22,EVI_20,EVI_18,ARVI_24,ARVI_22,ARVI_20
0,207924,0.123270,20.593474,92.319278,0.123270,0.149013,0.135740,0.172160,0.277432,0.416957,...,NaN,NaN,0.265774,-0.062729,-0.044806,-0.053286,-0.031504,0.103182,0.196157,0.104084
1,207925,0.126904,20.593474,92.319368,0.126904,0.152259,0.134524,0.172194,0.274602,0.407407,...,NaN,NaN,0.268246,-0.063119,-0.043866,-0.060732,-0.029327,0.077748,0.174194,0.095583
2,207926,0.127646,20.593474,92.319458,0.127646,0.148049,0.133457,0.170997,0.270080,0.385159,...,NaN,NaN,0.267290,-0.060337,-0.051282,-0.066977,-0.030601,0.076649,0.181818,0.086469
3,207927,0.129113,20.593474,92.319547,0.129113,0.149068,0.131735,0.171132,0.273589,0.421488,...,NaN,NaN,0.270677,-0.060366,-0.043573,-0.061078,-0.030662,0.076274,0.211585,0.108179
4,207928,0.129113,20.593474,92.319637,0.129113,0.149068,0.131735,0.171132,0.273589,0.421488,...,NaN,NaN,0.270677,-0.060366,-0.043573,-0.061078,-0.030662,0.076274,0.211585,0.108179
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150812,4880,0.130806,20.640635,92.331046,0.130806,0.138525,0.112374,0.164748,0.251812,0.363921,...,NaN,NaN,0.215479,-0.050465,-0.059588,-0.075492,-0.047207,0.082395,0.142656,0.086216
150813,4881,0.128662,20.640635,92.331136,0.128662,0.138799,0.112656,0.166406,0.294231,0.365145,...,NaN,NaN,0.207111,-0.043214,-0.061177,-0.073087,-0.046191,0.121484,0.136812,0.095845
150814,4882,0.135768,20.640635,92.331225,0.135768,0.139465,0.113089,0.161677,0.290386,0.351129,...,NaN,NaN,0.244828,-0.042895,-0.063812,-0.076557,-0.040290,0.096894,0.117319,0.087991
150815,4883,0.134755,20.640635,92.331315,0.134755,0.141119,0.111534,0.166519,0.269657,0.360406,...,NaN,NaN,0.197926,-0.050460,-0.067530,-0.068025,-0.043989,0.075702,0.104478,0.120045
150816,4884,0.135430,20.640635,92.331405,0.135430,0.137893,0.114888,0.166776,0.283765,0.350202,...,NaN,NaN,0.219512,-0.051264,-0.064907,-0.076419,-0.041358,0.069113,0.117526,0.084821

In [21]:
df_wide = df[['Lat','Long','MSAVI_18', 'MSAVI_20', 'MSAVI_22', 'MSAVI_24']]

In [23]:
df_wide = df_wide[(df_wide > 0).all(axis=1)]
df_wide

              Lat       Long  MSAVI_18  MSAVI_20  MSAVI_22  MSAVI_24
563     20.593474  92.324758  0.079744  0.061017  0.001318  0.068724
564     20.593474  92.324847  0.066159  0.050956  0.046474  0.082512
565     20.593474  92.324937  0.135404  0.176704  0.195824  0.175691
566     20.593474  92.325027  0.272492  0.230157  0.314284  0.233868
567     20.593474  92.325117  0.261931  0.243207  0.304228  0.207883
...           ...        ...       ...       ...       ...       ...
149195  20.617099  92.325925  0.326419  0.172338  0.196783  0.182439
149196  20.617099  92.326015  0.231723  0.100000  0.118800  0.132232
149197  20.617099  92.326105  0.083732  0.040438  0.048227  0.060690
149198  20.617099  92.326195  0.052340  0.030283  0.039510  0.041529
149199  20.617099  92.326285  0.028785  0.027170  0.028967  0.036531

[39179 rows x 6 columns]

In [25]:
df_wide['Change_18_20'] = (df['MSAVI_20']-df['MSAVI_18'])/df['MSAVI_18']
df_wide['Change_20_22'] = (df['MSAVI_22']-df['MSAVI_20'])/df['MSAVI_20']
df_wide['Change_22_24'] = (df['MSAVI_24']-df['MSAVI_22'])/df['MSAVI_22']

In [27]:
df_wide

,Lat,Long,MSAVI_18,MSAVI_20,MSAVI_22,MSAVI_24,Change_18_20,Change_20_22,Change_22_24
563,20.593474,92.324758,0.079744,0.061017,0.001318,0.068724,-0.234846,-0.978405,51.156906
564,20.593474,92.324847,0.066159,0.050956,0.046474,0.082512,-0.229805,-0.087960,0.775462
565,20.593474,92.324937,0.135404,0.176704,0.195824,0.175691,0.305008,0.108205,-0.102810
566,20.593474,92.325027,0.272492,0.230157,0.314284,0.233868,-0.155363,0.365519,-0.255869
567,20.593474,92.325117,0.261931,0.243207,0.304228,0.207883,-0.071485,0.250900,-0.316687
...,...,...,...,...,...,...,...,...,...
149195,20.617099,92.325925,0.326419,0.172338,0.196783,0.182439,-0.472036,0.141843,-0.072893
149196,20.617099,92.326015,0.231723,0.100000,0.118800,0.132232,-0.568450,0.187997,0.113068
149197,20.617099,92.326105,0.083732,0.040438,0.048227,0.060690,-0.517054,0.192621,0.258415
149198,20.617099,92.326195,0.052340,0.030283,0.039510,0.041529,-0.421419,0.304697,0.051097
149199,20.617099,92.326285,0.028785,0.027170,0.028967,0.036531,-0.056119,0.066133,0.261122

In [31]:
df_wide.to_csv('MSAVI.csv', index=False)